(** Module with common types. *)
MODULE Type ;

IMPORT SYSTEM;

TYPE
    (* Types *)
    BYTE* = SYSTEM.BYTE;
    WORD* = SYSTEM.CARD32;
    LONGWORD* = SYSTEM.CARD64;
    INT8* = SYSTEM.INT8;
    INT32* = SYSTEM.INT32;
    INT64* = SYSTEM.INT64;
    CARD8* = SYSTEM.CARD8;
    CARD32* = SYSTEM.CARD32;
    CARD64* = SYSTEM.CARD64;
    SET32* = SYSTEM.SET32;
    SET64* = SYSTEM.SET64;
    STRING* = POINTER TO ARRAY OF CHAR;

END Type.